mongo:  
  image: mongo:3.0.4 
  ports:  
   - "27018:27018"  
  volumes:  
   - './data:/data/db'  
application:  
  build: .  
  command: bash -c "npm install; nodemon app.js --color=always"  
  ports:  
   - "8080:3000"  
   #- "5858:5858"  
  volumes:  
   - ./app:/usr/src/app
  links:  
   - mongo  